#!/usr/bin/env python
import sys,shlex
import subprocess as sp
s1="git add -A "
s2="git commit -m \""+ sys.argv[1] +"\""
s3="git push"
args1 = shlex.split(s1)
args2 = shlex.split(s2)
args3 = shlex.split(s3)
sp.call(args1)
sp.call(args2)
sp.call(args3)